import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ArrowUp, BookOpen, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Eye, Flame, Mail, MapPin, Menu as MenuIcon, Minus, Navigation, Phone, Plus, ShoppingBag, ShoppingCart, Star, Trash2, Utensils, X, Wine, MessageCircle, Download} from 'lucide-react';
import {menuItems,categories} from './data';
import './styles.css';

const money = n => `€${n.toFixed(2)}`;
const navItems = [['home','Home'],['about','Our Heritage'],['menu','Menu & Ordering'],['brochure','Digital Brochure'],['reserve','Book a Table'],['location','Location & Map']];

function App(){
  const [mobileOpen,setMobileOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[activeCat,setActiveCat]=useState('all');
  const [selected,setSelected]=useState(null),[qty,setQty]=useState(1),[size,setSize]=useState('Standard'),[instructions,setInstructions]=useState('');
  const [cart,setCart]=useState([]),[delivery,setDelivery]=useState(false),[brochure,setBrochure]=useState(false),[success,setSuccess]=useState(false),[orderNo,setOrderNo]=useState('');
  const [reservation,setReservation]=useState({name:'',email:'',phone:'',date:'',time:'19:00',guests:'2',msg:''});
  const [reservationSuccess,setReservationSuccess]=useState(false);
  const [reservationRef,setReservationRef]=useState('');
  const [newsletterEmail,setNewsletterEmail]=useState('');
  const [newsletterSuccess,setNewsletterSuccess]=useState(false);
  const filtered=useMemo(()=>activeCat==='all'?menuItems:menuItems.filter(i=>i.category===activeCat),[activeCat]);
  const cartCount=cart.reduce((a,i)=>a+i.quantity,0), subtotal=cart.reduce((a,i)=>a+i.unitPrice*i.quantity,0), tax=subtotal*.09, total=subtotal+tax+(delivery?4.5:0);
  const sizeExtra=size==='Large'?3.5:size==='Family Share'?8:0;
  const modalTotal=selected?(selected.price+sizeExtra)*qty:0;

  useEffect(()=>{ if(!reservation.date) setReservation(r=>({...r,date:new Date().toISOString().slice(0,10)})); },[]);
  useEffect(()=>{document.body.classList.toggle('lock',!!(selected||brochure||cartOpen||success));return()=>document.body.classList.remove('lock')},[selected,brochure,cartOpen,success]);

  const addItem=(item,chosenSize='Standard',notes='',amount=1)=>{
    const extra=chosenSize==='Large'?3.5:chosenSize==='Family Share'?8:0;
    const key=`${item.id}-${chosenSize}-${notes}`;
    setCart(c=>{const idx=c.findIndex(x=>x.key===key); if(idx>-1){const n=[...c];n[idx]={...n[idx],quantity:n[idx].quantity+amount};return n}return [...c,{key,id:item.id,name:item.name,size:chosenSize,unitPrice:item.price+extra,quantity:amount,image:item.image,instructions:notes}]});
    setCartOpen(true);
  };
  const openItem=item=>{setSelected(item);setQty(1);setSize('Standard');setInstructions('')};
  const quickAdd=item=>addItem(item);
  const changeQty=(key,delta)=>setCart(c=>c.map(x=>x.key===key?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0));
  const removeItem=key=>setCart(c=>c.filter(x=>x.key!==key));
  const submitReservation=e=>{e.preventDefault(); const ref='#RS-'+Math.floor(1000+Math.random()*9000); setReservationRef(ref); setReservationSuccess(true); setReservation(r=>({...r,name:'',email:'',phone:'',msg:''}))};
  const checkout=()=>{if(!cart.length){alert('Your cart is empty. Please add items before checkout.');return} const n='#CP-'+Math.floor(1000+Math.random()*9000);setOrderNo(n);setCart([]);setCartOpen(false);setSuccess(true)};

  return <div className="app">
    <Header cartCount={cartCount} cartOpen={()=>setCartOpen(true)} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}/>
    <main>
      <Hero/>
      <Announcement/>
      <Heritage/>
      <MenuSection filtered={filtered} activeCat={activeCat} setActiveCat={setActiveCat} openItem={openItem} quickAdd={quickAdd}/>
      <BrochureSection open={()=>setBrochure(true)}/>
      <Reservation reservation={reservation} setReservation={setReservation} onSubmit={submitReservation}/>
      <Location/>
    </main>
    <Footer newsletterEmail={newsletterEmail} setNewsletterEmail={setNewsletterEmail} onSubscribe={()=>{if(newsletterEmail.trim())setNewsletterSuccess(true)}}/>
    <Floating/>
    {selected&&<ItemModal item={selected} qty={qty} setQty={setQty} size={size} setSize={setSize} instructions={instructions} setInstructions={setInstructions} total={modalTotal} close={()=>setSelected(null)} add={()=>{addItem(selected,size,instructions,qty);setSelected(null)}}/>}
    {brochure&&<BrochureModal close={()=>setBrochure(false)}/>} 
    {cartOpen&&<CartDrawer cart={cart} delivery={delivery} setDelivery={setDelivery} subtotal={subtotal} tax={tax} total={total} changeQty={changeQty} removeItem={removeItem} close={()=>setCartOpen(false)} checkout={checkout}/>} 
    {success&&<SuccessModal orderNo={orderNo} close={()=>setSuccess(false)}/>}
    {reservationSuccess&&<ReservationSuccessModal reference={reservationRef} close={()=>setReservationSuccess(false)}/>}
    {newsletterSuccess&&<NewsletterSuccessModal close={()=>{setNewsletterSuccess(false);setNewsletterEmail('')}}/>} 
  </div>
}

function Header({cartCount,cartOpen,mobileOpen,setMobileOpen}){return <header className="site-header"><div className="nav-shell"><a href="#home" className="brand"><span className="brand-mark">CP</span><span><strong>CINEMA PARADISO</strong><small>Italian Restaurant & Wine Bar</small></span></a><nav className="desktop-nav">{navItems.map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav><div className="nav-actions"><button className="cart-pill" onClick={cartOpen}><ShoppingBag size={17}/><span>Order Cart</span><b>{cartCount}</b></button><button className="menu-toggle" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Open menu">{mobileOpen?<X/>:<MenuIcon/>}</button></div></div>{mobileOpen&&<nav className="mobile-nav">{navItems.map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMobileOpen(false)}>{label}</a>)}</nav>}</header>}

function Hero(){return <section id="home" className="hero"><div className="hero-media"><video autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=2200&q=85"><source src="https://assets.mixkit.co/videos/preview/mixkit-hands-pouring-wine-into-a-glass-41584-large.mp4" type="video/mp4"/></video><div className="hero-image-fallback"/></div><div className="hero-overlay"/><div className="hero-content"><span className="eyebrow live"><i/> Authentic Italian Ambiance in Amsterdam</span><p className="hero-kicker">A dinner worth remembering</p><h1>Cinema <em>Paradiso</em></h1><p className="hero-copy">Traditional wood-fired Neapolitan pizzas, handcrafted artisanal pastas, and our sommelier's finest wine selections — served in an unforgettable cinematic setting.</p><div className="hero-actions"><a href="#menu" className="btn btn-primary"><Utensils size={17}/> Explore & Order Menu</a><a href="#reserve" className="btn btn-ghost"><CalendarDays size={17}/> Reserve a Table</a></div><div className="hero-stats"><span><strong>4.9</strong> guest rating</span><span><strong>50+</strong> cellar wines</span><span><strong>100%</strong> DOP imports</span></div></div><div className="scroll-cue"><span>Scroll</span><ChevronDown size={16}/></div></section>}
function Announcement(){return <section className="announce-wrap"><div className="announcement"><div><span className="gold-chip">Special Announcement</span><h3>Now also open on Sundays!</h3><p>Tue through Sun: <strong>19:00 — 23:00</strong> <i/> Monday Closed</p></div><a href="#reserve" className="btn btn-gold">Book Sunday Table <ArrowRight size={16}/></a></div></section>}
function Heritage(){return <section id="about" className="section heritage"><div className="heritage-copy"><span className="eyebrow">Our Heritage & Story</span><h2>Where passion for cinema meets culinary mastery.</h2><p className="lead">Inspired by the timeless Italian masterpiece <em>Cinema Paradiso</em>, our restaurant celebrates the harmonious union of exquisite food, warm hospitality, and cinematic romance.</p><p>Every ingredient is meticulously sourced — from authentic San Marzano tomatoes grown in volcanic Campanian soil to artisan cheeses and cold-pressed extra virgin olive oils. Our chefs treat every plate as a masterpiece.</p><div className="metrics"><div><b>100%</b><span>Imported DOP</span></div><div><b>50+</b><span>Cellar Wines</span></div><div><b>4.9★</b><span>Guest Rating</span></div></div></div><div className="heritage-gallery"><div className="gallery-glow"/><img className="g1" src="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=85" alt="Restaurant interior"/><img className="g2" src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1000&q=85" alt="Wood fired pizza"/><span className="gallery-caption">Food · Film · La Dolce Vita</span></div></section>}
function MenuSection({filtered,activeCat,setActiveCat,openItem,quickAdd}){return <section id="menu" className="section menu-section"><div className="section-head"><span className="eyebrow">Gastronomic Selection</span><h2>Our Interactive Menu</h2><p>Explore artisanal dishes, inspect ingredients, choose your portion, and add favorites to your order.</p></div><div className="category-row">{categories.map(([id,label])=><button key={id} className={activeCat===id?'category active':'category'} onClick={()=>setActiveCat(id)}>{label}</button>)}</div><div className="menu-grid">{filtered.map((item,i)=><MenuCard key={item.id} item={item} index={i} openItem={openItem} quickAdd={quickAdd}/>)}</div></section>}
function MenuCard({item,index,openItem,quickAdd}){return <article className={`menu-card card-${index%3}`}><button className="food-photo" onClick={()=>openItem(item)}><img src={item.image} alt={item.name}/><span className="photo-shade"/>{item.badge&&<span className="food-badge">{item.badge}</span>}<span className="rating"><Star size={12} fill="currentColor"/> {item.rating}</span><span className="food-category">{item.category}</span><span className="photo-cta"><Eye size={15}/> View dish</span></button><div className="menu-card-body"><div className="title-line"><h3 onClick={()=>openItem(item)}>{item.name}</h3><strong>{money(item.price)}</strong></div><p>{item.description}</p><div className="card-bottom"><button className="details" onClick={()=>openItem(item)}>Inspect details <ChevronRight size={14}/></button><button className="add-btn" onClick={()=>quickAdd(item)}><ShoppingCart size={15}/> Add</button></div></div></article>}
function BrochureSection({open}){return <section id="brochure" className="section brochure"><div className="brochure-card"><div className="brochure-art"><div className="film-frame">CP</div><span>MENU<br/>2026</span></div><div className="brochure-copy"><span className="eyebrow">Digital Brochure</span><h2>Seasonal menu & wine list.</h2><p>Browse the complete selection offline or share it with guests. View the official high-resolution menu catalog instantly.</p><div className="brochure-actions"><button className="btn btn-primary" onClick={open}><BookOpen size={17}/> View Menu Booklet</button><button className="btn btn-gold" onClick={()=>alert('Downloading official Cinema Paradiso Menu & Wine Catalog 2026 (PDF)...')}><Download size={17}/> Download PDF</button></div></div></div></section>}
function Reservation({reservation,setReservation,onSubmit}){const set=(k,v)=>setReservation(r=>({...r,[k]:v}));return <section id="reserve" className="section reservation"><div className="reservation-card"><div className="reservation-head"><span className="eyebrow">Table Booking</span><h2>Reserve your experience.</h2><p>Secure your table instantly. For parties larger than 10, please contact us directly via phone or WhatsApp.</p></div><form onSubmit={onSubmit}><div className="form-grid two"><Field label="Your Name *"><input required value={reservation.name} onChange={e=>set('name',e.target.value)} placeholder="e.g. Marco Rossi"/></Field><Field label="Email Address *"><input required type="email" value={reservation.email} onChange={e=>set('email',e.target.value)} placeholder="marco@example.com"/></Field></div><div className="form-grid three"><Field label="Phone Number *"><input required type="tel" value={reservation.phone} onChange={e=>set('phone',e.target.value)} placeholder="+31 20 123 4567"/></Field><Field label="Date *"><input required type="date" min={new Date().toISOString().slice(0,10)} value={reservation.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Time *"><select value={reservation.time} onChange={e=>set('time',e.target.value)}>{['19:00','19:30','20:00','20:30','21:00','21:30'].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="form-grid two"><Field label="Number of Guests *"><select value={reservation.guests} onChange={e=>set('guests',e.target.value)}>{['1','2','3','4','5','6+'].map(x=><option key={x} value={x}>{x} {x==='2'?'Guests (Romantic)':'Guest'+(x==='1'?'':'s')}</option>)}</select></Field><Field label="Special Requests / Dietary Notes"><input value={reservation.msg} onChange={e=>set('msg',e.target.value)} placeholder="Allergies, anniversary, seating preference..."/></Field></div><button className="btn btn-gold submit" type="submit"><Check size={17}/> Confirm Table Reservation</button></form></div></section>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Location(){return <section id="location" className="section location"><div className="section-head"><span className="eyebrow">Visit Our Restaurant</span><h2>Location & Directions</h2><p>Situated in the vibrant cultural heart of Amsterdam. Drop by for dinner or pick up your online order.</p></div><div className="location-grid"><div className="location-card"><span className="gold-chip">Amsterdam Venue</span><h3>Cinema Paradiso</h3><p>Verwisselt 42<br/>1012 AB Amsterdam, Netherlands</p><div className="contact-list"><span><Phone/> +31 20 555 0192</span><span><Mail/> concierge@cinemaparadiso.nl</span><span><Clock3/> Tue — Sun: 19:00 — 23:00</span></div><a className="directions" target="_blank" rel="noreferrer" href="https://maps.google.com/?q=Verwisselt+42+Amsterdam"><Navigation size={15}/> Get Directions on Google Maps</a></div><div className="map-card"><iframe title="Cinema Paradiso map" src="https://www.openstreetmap.org/export/embed.html?bbox=4.87%2C52.35%2C4.92%2C52.38&layer=mapnik&marker=52.3676%2C4.8941" loading="lazy"/><div className="map-label"><MapPin size={15}/> Cinema Paradiso · Amsterdam</div></div></div></section>}
function Footer({newsletterEmail,setNewsletterEmail,onSubscribe}){return <footer><div className="footer-grid"><div><a className="brand footer-brand" href="#home"><span className="brand-mark">CP</span><span><strong>CINEMA PARADISO</strong><small>Italian Restaurant & Wine Bar</small></span></a><p>An authentic cinematic Italian dining experience in the heart of Amsterdam. Handcrafted pastas, artisanal wood-fired pizzas, and exquisite wines.</p><div className="socials"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram">IG</a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook">FB</a><a href="https://www.tripadvisor.com/" target="_blank" rel="noreferrer" aria-label="Tripadvisor">TA</a></div></div><div><h4>Opening Hours</h4><p>Tuesday — Thursday <b>19:00 — 23:00</b></p><p>Friday — Saturday <b>19:00 — 23:30</b></p><p>Sunday <b>19:00 — 23:00</b></p><p>Monday <i>Closed</i></p></div><div><h4>Contact & Location</h4><p><MapPin/> Verwisselt 42, 1012 AB Amsterdam</p><p><Phone/> +31 20 555 0192</p><p><Mail/> concierge@cinemaparadiso.nl</p></div><div><h4>Newsletter & Offers</h4><p>Subscribe for seasonal wine tastings and exclusive menu releases.</p><form className="newsletter" onSubmit={e=>{e.preventDefault();onSubscribe()}}><input required type="email" value={newsletterEmail} onChange={e=>setNewsletterEmail(e.target.value)} placeholder="Your email address"/><button type="submit">Subscribe</button></form></div></div><div className="footer-bottom">© 2026 Cinema Paradiso Italian Restaurant Amsterdam. All rights reserved. <span>Crafted with passion & cinematic elegance.</span></div></footer>}
function Floating(){return <div className="floating"><a className="float-top" href="#home" title="Back to top"><ArrowUp size={18}/></a><a className="whatsapp" href="https://wa.me/31205550192?text=Hello%20Cinema%20Paradiso,%20I%20would%20like%20to%20inquire%20about..." target="_blank" rel="noreferrer" title="Chat on WhatsApp"><MessageCircle/></a></div>}
function ItemModal({item,qty,setQty,size,setSize,instructions,setInstructions,total,close,add}){return <Modal onClose={close}><div className="item-modal"><div className="modal-image"><img src={item.image} alt={item.name}/><span className="food-category">{item.category}</span></div><div className="modal-body"><div className="modal-title"><div><h3>{item.name}</h3><p>{item.description}</p></div><strong>{money(item.price)}</strong></div><div><span className="modal-label">Fresh Ingredients & Allergens</span><div className="tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div></div><div><span className="modal-label">Select Portion / Size</span><div className="sizes">{[['Standard',0],['Large',3.5],['Family Share',8]].map(([s,e])=><button key={s} className={size===s?'selected':''} onClick={()=>setSize(s)}><b>{s}</b><small>{e?`+€${e.toFixed(2)}`:'Included'}</small></button>)}</div></div><Field label="Special Cooking Instructions"><input value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="e.g. Extra virgin olive oil, well done..."/></Field><div className="modal-add"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(Math.min(20,qty+1))}><Plus/></button></div><button className="btn btn-primary grow" onClick={add}><ShoppingCart size={17}/> Add to Order — {money(total)}</button></div></div></div></Modal>}
function BrochureModal({close}){return <Modal onClose={close}><div className="brochure-modal"><div className="modal-head"><div><span className="eyebrow">Official Seasonal Digital Booklet</span><h3>Cinema Paradiso — Menu Catalog 2026</h3></div><button onClick={close}><X/></button></div><div className="brochure-preview"><h4>Authentic Italian Flavors in Amsterdam</h4><p>Our complete physical brochure features sommelier wine pairings, chef's tasting courses, artisan wood-fired pizzas, handmade pastas, and exquisite traditional desserts.</p><div className="brochure-pages"><img src="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=700&q=85" alt="Menu page"/><img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=700&q=85" alt="Menu page"/><img src="https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=700&q=85" alt="Menu page"/></div></div><div className="modal-actions"><button className="btn btn-ghost" onClick={close}>Close</button><a className="btn btn-gold" href="/cinema-paradiso-menu-2026.pdf" download><Download size={16}/> Download Full PDF</a></div></div></Modal>}
function CartDrawer({cart,delivery,setDelivery,subtotal,tax,total,changeQty,removeItem,close,checkout}){return <div className="drawer-layer"><button className="drawer-backdrop" onClick={close} aria-label="Close cart"/><aside className="cart-drawer"><div className="drawer-head"><div><span className="eyebrow">Your Order</span><h3>Order Summary</h3><small>{cart.reduce((a,i)=>a+i.quantity,0)} items in cart</small></div><button onClick={close}><X/></button></div><div className="mode-switch"><button className={!delivery?'active':''} onClick={()=>setDelivery(false)}>Pickup · Amsterdam</button><button className={delivery?'active':''} onClick={()=>setDelivery(true)}>Delivery · +€4.50</button></div><div className="drawer-items">{cart.length===0?<div className="empty"><ShoppingBag/><h4>Your cart is currently empty</h4><p>Explore the menu and add authentic Italian delicacies.</p></div>:cart.map(item=><div className="cart-item" key={item.key}><img src={item.image} alt={item.name}/><div><h4>{item.name}</h4><span>{item.size} · {money(item.unitPrice)}</span>{item.instructions&&<small>Note: “{item.instructions}”</small>}<div className="cart-line"><div className="mini-qty"><button onClick={()=>changeQty(item.key,-1)}><Minus/></button><b>{item.quantity}</b><button onClick={()=>changeQty(item.key,1)}><Plus/></button></div><strong>{money(item.unitPrice*item.quantity)}</strong></div></div><button className="trash" onClick={()=>removeItem(item.key)}><Trash2/></button></div>)}</div><div className="drawer-footer"><div><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Estimated Tax (9%)</span><b>{money(tax)}</b></p>{delivery&&<p><span>Delivery Fee</span><b>€4.50</b></p>}<p className="grand"><span>Total Amount</span><b>{money(total)}</b></p></div><button className="btn btn-gold checkout" onClick={checkout}>Proceed to Secure Checkout <ArrowRight size={17}/></button></div></aside></div>}
function ReservationSuccessModal({reference,close}){return <Modal onClose={close}><div className="success-modal"><div className="success-icon"><Check/></div><span className="eyebrow">Table Reserved Successfully</span><h3>Ci vediamo presto.</h3><small>Reservation: {reference}</small><p>Your table request has been received. We look forward to welcoming you for an Italian evening in Amsterdam.</p><a className="btn btn-primary" href="#location" onClick={close}>View Location</a></div></Modal>}
function NewsletterSuccessModal({close}){return <Modal onClose={close}><div className="success-modal"><div className="success-icon"><Mail/></div><span className="eyebrow">You're on the list</span><h3>Grazie!</h3><p>You'll receive seasonal wine tastings, menu releases, and special Cinema Paradiso offers.</p><button className="btn btn-primary" onClick={close}>Done</button></div></Modal>}
function SuccessModal({orderNo,close}){return <Modal onClose={close}><div className="success-modal"><div className="success-icon"><Check/></div><span className="eyebrow">Order Placed Successfully!</span><h3>Buon Appetito!</h3><small>Order ID: {orderNo}</small><p>Thank you for ordering with Cinema Paradiso. Your delicious authentic Italian meal is being prepared with passion in our kitchen.</p><button className="btn btn-primary" onClick={close}>Return to Website</button></div></Modal>}
function Modal({children,onClose}){return <div className="modal-layer" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>{children}</div>}

createRoot(document.getElementById('root')).render(<App/>);
